# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 048bfcf856a8a16365c57acd184cd7ff08f700301c3f939b12c389ccbf71a05ce5a1dbed80c848feede01067e446096cd555f42d6b371ed4a5ae160312ef5f8c

test:
  secret_key_base: 9b7f1689a7d56745c19b84088fd59dd14f504b8d12f620c9f0dadbc47d1fb8a5c234d1331ffd4f87390944092155d1843f48da1f0dd0520833f62b5ad79cfc7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
